### ISSUE TITLE
Costes Randomization only on channel B intereferes with graphical display

### ISSUE THREAD

**Issue by emiglietta** [BIOP/ijp-jacop-b#2]
Using Costes auto-threshold only on channel B results in weird or no graphical display (depending on wether Costes Randomization Mask is selected). 

A report of various input/output scenarios as well as the general GUI options (only the ones mentioned in the report are changed) below:

[Report BIOP JACoP.pdf](https://github.com/BIOP/ijp-jacop-b/files/10179744/Report.BIOP.JACoP.pdf)
![BIOP JACoP GUI options](https://user-images.githubusercontent.com/58238709/206287909-90a4f5f7-ec6b-407c-95ae-c0936e0a4a63.PNG)

**Comment by romainGuiet** [comment]
Thank you for the very detailed report, much appreciated !
Best,
Romain

**Comment by NicoKiaru** [comment]
Normally fixed in https://github.com/BIOP/ijp-jacop-b/commit/6db2df2d911e1b3c5f8e61b5894e66719bb264a8 and https://github.com/BIOP/ijp-jacop-b/commit/ffb26e5e89279565f7016ef1f656c4bc739b26a8
