### ISSUE TITLE
Costes autothreshold

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/ijp-jacop-b#3]
[post on forum ]( https://forum.image.sc/t/inconsistent-costes-threshold-results-across-different-plugins/94558/1)

in [coloc2](https://github.com/fiji/Colocalisation_Analysis/blob/master/src/main/java/sc/fiji/coloc/algorithms/AutoThresholdRegression.java)

In [BIOP-JACoP](https://github.com/BIOP/ijp-jacop-b/blob/f7e4fa8d8fba1231761dd49a1fd9e02b29a04c88/src/main/java/ch/epfl/biop/coloc/utils/ImageColocalizer.java#L396)

**Comment by NicoKiaru** [comment]
Decision: we use coloc2 implementation: https://github.com/BIOP/ijp-jacop-b/commit/3f383ecf8e0e21d1a6055e33c64e0ad35079f987
